"""create bootstrap keys table

Revision ID: 9eb8d0b86cbc
Revises:
Create Date: 2025-10-27 19:26:23.661701

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eb8d0b86cbc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bootstrap_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("key_hint", sa.String(length=4), nullable=False),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expiration_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_bootstrap_keys_group", "bootstrap_keys", ["group"], unique=False)
    op.create_index(op.f("ix_bootstrap_keys_id"), "bootstrap_keys", ["id"], unique=False)
    op.create_index("ix_bootstrap_keys_is_active", "bootstrap_keys", ["is_active"], unique=False)
    op.create_index(op.f("ix_bootstrap_keys_key_hash"), "bootstrap_keys", ["key_hash"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bootstrap_keys_key_hash"), table_name="bootstrap_keys")
    op.drop_index("ix_bootstrap_keys_is_active", table_name="bootstrap_keys")
    op.drop_index(op.f("ix_bootstrap_keys_id"), table_name="bootstrap_keys")
    op.drop_index("ix_bootstrap_keys_group", table_name="bootstrap_keys")
    op.drop_table("bootstrap_keys")
    # ### end Alembic commands ###
